spring.application.name=producer
spring.devtools.livereload.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/java
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
